{
  config,
  pkgs,
  ...
}: {
  wayland.windowManager.hyprland = {
    enable = true;
    settings = {
      autogenerated = 0;

      env = [
        "XCURSOR_SIZE,16"
        "HYPRCURSOR_SIZE,24"
      ];

      "$terminal" = "ghostty";
      "$browser" = "zen";
      "$menu" = "wofi --show drun";

      general = {
        gaps_in = 3;
        gaps_out = 2;
        border_size = 2;
        resize_on_border = false;
        allow_tearing = false;
        layout = "dwindle";
      };

      dwindle = {
        pseudotile = true;
        preserve_split = true;
      };

      master = {
        new_status = "master";
      };

      misc = {
        force_default_wallpaper = 0;
        disable_hyprland_logo = true;
      };

      input = {
        follow_mouse = 1;
        sensitivity = 0;
        touchpad = {
          natural_scroll = true;
        };
      };

      gestures = {
        workspace_swipe = false;
      };
    };
  };
}
